-- K2: 리드폼별 IP 차단 + 차단 접속(제출 시도) 로그.
-- 관리자가 특정 IP/대역을 차단하면 그 IP의 공개 리드폼 제출을 거부하고, 시도 내역을 로그로 남긴다.

create table ip_blocks (
    id          bigint generated by default as identity primary key,
    form_id     bigint not null references forms (id),
    pattern     varchar(64) not null,   -- 단일 IP 또는 CIDR 대역 (예: 1.2.3.4 / 1.2.3.0/24)
    reason      varchar(255),           -- 차단 사유 메모(선택)
    created_at  timestamp(6) with time zone not null
);
create index idx_ip_blocks_form on ip_blocks (form_id);

-- 차단된 IP가 제출을 시도한 로그(확인용). 리드로는 저장되지 않는다.
create table ip_block_hits (
    id              bigint generated by default as identity primary key,
    form_id         bigint not null references forms (id),
    ip              varchar(64) not null,
    matched_pattern varchar(64),        -- 어떤 차단 규칙에 걸렸는지
    user_agent      varchar(1024),
    referer         varchar(1024),
    created_at      timestamp(6) with time zone not null
);
create index idx_ip_block_hits_form on ip_block_hits (form_id, created_at);
