-- M8: 재사용 HTML 요소 라이브러리. 미리 만든 HTML 조각(헤더·푸터·CTA 등)을 저장해두고
-- 랜딩/폼의 HTML 블록에 복사 삽입(스냅샷)해서 재사용한다. 동의문서 관리와 유사 패턴.
create table html_components (
    id         bigint generated by default as identity primary key,
    owner_id   bigint not null references users (id),
    name       varchar(255) not null,          -- 관리용 이름 (예: "메인 상단 헤더")
    category   varchar(40) not null default 'ETC', -- 분류: HEADER|FOOTER|CTA|CONTENT|ETC
    html       text not null default '',        -- 삽입될 HTML 조각
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

create index idx_html_components_owner on html_components (owner_id);
