-- I4/I5: 요소 상호작용 이벤트(경량). 전환 퍼널의 중간 단계(폼 열기)와 주요 클릭을 기록한다.
-- 방문(visits) → 폼 열기(form_open) → 접수(leads) 퍼널 구성. 개인정보 최소화(IP는 해시).
create table interaction_events (
    id              bigint generated by default as identity primary key,
    owner_id        bigint not null references users (id),
    landing_page_id bigint,
    form_id         bigint,
    event_type      varchar(40) not null,   -- form_open | cta_click 등
    target          varchar(255),           -- 클릭 대상 라벨(버튼 텍스트 등)
    ip_hash         varchar(64),            -- 고유 추정용 SHA-256 해시
    created_at      timestamp(6) with time zone not null
);
create index idx_events_owner_created on interaction_events (owner_id, created_at);
