-- 리드 관리 고도화 + 외부 연동
-- 1) 리드별 태그(jsonb 문자열 배열) 2) 리드 메모/이력 3) 계정별 연동 설정(텔레그램·구글시트)

-- 1) 리드 태그: 자유 태그 문자열 배열. 없으면 null.
alter table leads add column tags jsonb;

-- 2) 리드 메모/이력: 사용자 메모(MEMO) + 상태변경 등 자동 이력(SYSTEM).
create table lead_notes (
    id         bigint generated by default as identity primary key,
    lead_id    bigint not null references leads (id) on delete cascade,
    owner_id   bigint not null references users (id),
    kind       varchar(20) not null default 'MEMO', -- MEMO | SYSTEM
    body       text not null,
    created_at timestamp(6) with time zone not null
);
create index idx_lead_notes_lead on lead_notes (lead_id, created_at);

-- 3) 계정별 연동 설정: 텔레그램 봇 + 구글시트 Apps Script 웹훅. 계정당 1행(owner_id PK).
--    토큰/URL 은 사용자가 직접 발급해 입력하는 값(개인 리소스). 시크릿은 코드/깃에 남기지 않는다.
create table integration_settings (
    owner_id           bigint primary key references users (id),
    telegram_enabled   boolean not null default false,
    telegram_bot_token varchar(200),
    telegram_chat_id   varchar(100),
    sheets_enabled     boolean not null default false,
    sheets_webhook_url varchar(1000),
    updated_at         timestamp(6) with time zone not null
);
