-- 광고주 하위계정 포털 — 기반 스키마 (A1)
-- 마케터가 광고주 계정을 초대·생성하고, 리드폼 단위로 열람 권한을 부여한다.
-- 구조: 1 마케터 : N 광고주 / 1 광고주 : N 리드폼(소속 마케터 것만) / 1 리드폼 : 1 광고주
-- 설계 정본: docs/ADVERTISER-PORTAL-PLAN.md

-- 1) 계정 확장 -------------------------------------------------------------
-- 광고주는 공개 랜딩/폼이 없으므로 서브도메인이 필요 없다(마케터만 보유).
alter table users alter column subdomain drop not null;

-- 소유 마케터. 광고주 계정만 채우고 마케터/관리자는 null.
alter table users add column parent_user_id bigint references users (id);
-- 광고주 부가정보(회사명은 목록 표시용, memo 는 마케터만 보는 내부 메모)
alter table users add column company varchar(120);
alter table users add column memo varchar(500);
-- 계정 정지/해지. false 면 로그인·토큰 재발급 모두 차단.
alter table users add column active boolean not null default true;
-- 화이트라벨: 마케터 계정에 저장하고 소속 광고주 화면에 적용한다.
alter table users add column brand_logo_url varchar(500);
alter table users add column brand_color varchar(20);

create index idx_users_parent on users (parent_user_id);

-- 2) 광고주 초대 -----------------------------------------------------------
-- 마케터가 초대 링크를 발급하고, 광고주가 링크로 들어와 직접 비밀번호를 설정한다.
-- 토큰은 절대 원문으로 저장하지 않는다(해시만) — DB 유출 시 계정 탈취 방지.
create table advertiser_invites (
    id              bigint generated by default as identity primary key,
    marketer_id     bigint not null references users (id) on delete cascade,
    email           varchar(255) not null,
    name            varchar(120),
    company         varchar(120),
    token_hash      varchar(100) not null unique,
    expires_at      timestamp(6) with time zone not null,
    accepted_at     timestamp(6) with time zone,
    -- 수락으로 만들어진 광고주 계정. 그 계정을 나중에 삭제해도 초대 이력은 남긴다(set null).
    -- on delete 를 지정하지 않으면 FK 가 광고주 삭제를 막아버린다.
    created_user_id bigint references users (id) on delete set null,
    created_at      timestamp(6) with time zone not null
);
create index idx_advertiser_invites_marketer on advertiser_invites (marketer_id, created_at);

-- 3) 리드폼 열람 권한 ------------------------------------------------------
-- 광고주 권한의 단일 출처. 여기 없는 리드폼은 광고주가 접근할 수 없다.
-- display_name: 마케터 내부 폼명(예: A병원_7월_리타겟_v3) 대신 광고주에게 보여줄 이름.
-- expires_at:   계약 종료 시 자동 차단(null = 무기한).
create table advertiser_form_grants (
    id            bigint generated by default as identity primary key,
    advertiser_id bigint not null references users (id) on delete cascade,
    form_id       bigint not null references forms (id) on delete cascade,
    display_name  varchar(120),
    expires_at    timestamp(6) with time zone,
    can_status    boolean not null default true,
    can_memo      boolean not null default true,
    can_export    boolean not null default true,
    created_at    timestamp(6) with time zone not null,
    -- 1 리드폼 : 1 광고주 강제. 실수로 두 광고주에게 같은 폼이 열리는 사고를 DB가 차단한다.
    constraint uq_advertiser_form_grants_form unique (form_id)
);
create index idx_advertiser_form_grants_advertiser on advertiser_form_grants (advertiser_id);

-- 4) 광고주 처리 상태 ------------------------------------------------------
-- 마케터의 leads.status 와 분리한다. 같은 컬럼을 쓰면 광고주가 마케터의 분류(불량 등)를 덮어쓴다.
-- advertiser_status: 신규 | 확인 | 통화완료 | 부재 | 종료 (고정 5개)
alter table leads add column advertiser_status varchar(30);
alter table leads add column advertiser_status_at timestamp(6) with time zone;
-- 광고주가 리드를 최초로 열어본 시각. 마케터 목록의 '광고주 확인' 마크 + 처리속도 리포트의 재료.
alter table leads add column advertiser_seen_at timestamp(6) with time zone;

create index idx_leads_advertiser_seen on leads (form_id, advertiser_seen_at);

-- 5) 메모 가시성 -----------------------------------------------------------
-- MARKETER_ONLY = 마케터만 / ALL = 마케터+광고주 공유.
-- 기본값을 MARKETER_ONLY 로 둬서 기존 메모(마케터 내부 기록)가 광고주에게 노출되지 않는다.
-- not null default 라 기존 행은 자동으로 MARKETER_ONLY 로 채워진다(별도 UPDATE 불필요).
alter table lead_notes add column visibility varchar(20) not null default 'MARKETER_ONLY';

-- 6) 광고주 감사 로그 ------------------------------------------------------
-- 개인정보 취급 추적 + 분쟁 대비. 광고주의 열람·다운로드·상태변경을 전부 남긴다.
-- ⚠️ 일부러 FK 를 걸지 않는다: 감사 로그는 append-only 이력이라
--    광고주 계정을 삭제해도 남아야 한다(cascade 로 함께 지워지면 감사 기능이 무의미해진다).
--    계정이 사라진 뒤에도 누구였는지 알 수 있도록 이메일을 스냅샷으로 함께 저장한다.
create table advertiser_access_logs (
    id               bigint generated by default as identity primary key,
    advertiser_id    bigint not null,
    advertiser_email varchar(255),
    form_id          bigint,
    lead_id          bigint,
    action           varchar(30) not null, -- LOGIN | VIEW_LEAD | EXPORT | STATUS | MEMO | IMPERSONATE
    detail           varchar(300),
    ip               varchar(64),
    created_at       timestamp(6) with time zone not null
);
create index idx_advertiser_access_logs_advertiser
    on advertiser_access_logs (advertiser_id, created_at desc);

-- 7) 알림 발송 이력 --------------------------------------------------------
-- "리드 안 왔다 / 알림 못 받았다" 클레임에 대한 반박 근거.
-- 기존에는 발송 실패가 로그(log.warn)로만 남아 DB에 증거가 없었다.
-- 감사 로그와 같은 이유로 FK 없음(이력 보존).
create table notification_logs (
    id                bigint generated by default as identity primary key,
    lead_id           bigint,
    form_id           bigint,
    recipient_user_id bigint,
    channel           varchar(20) not null, -- TELEGRAM | SHEETS
    success           boolean not null,
    error_message     varchar(300),
    created_at        timestamp(6) with time zone not null
);
create index idx_notification_logs_lead on notification_logs (lead_id, created_at);
