-- 광고주 비밀번호 재설정
-- 광고주는 자주 쓰는 사용자가 아니라 비밀번호를 잊는 일이 흔하다. 그런데 초대는
-- "이미 등록된 이메일"을 거부하므로, 재설정 수단이 없으면 계정을 삭제하고 다시 초대하는 방법밖에 없다
-- (그러면 감사 로그·열람 이력이 끊긴다). 그래서 마케터가 재설정 링크를 발급하는 경로를 만든다.
--
-- ⚠️ 마케터가 임시 비밀번호를 직접 정해주는 방식은 쓰지 않는다.
--    마케터가 광고주의 비밀번호를 알게 되면 "내가 안 봤다"는 광고주 주장과 감사 로그가 충돌해
--    기록의 증거 가치가 사라진다(초대 링크 방식과 같은 이유).
create table advertiser_password_resets (
    id            bigint generated by default as identity primary key,
    advertiser_id bigint not null references users (id) on delete cascade,
    -- 발급한 마케터(이력 추적용). 마케터 계정이 지워져도 기록은 남긴다.
    issued_by     bigint references users (id) on delete set null,
    token_hash    varchar(100) not null unique, -- 토큰 원문은 저장하지 않는다
    expires_at    timestamp(6) with time zone not null,
    used_at       timestamp(6) with time zone,
    created_at    timestamp(6) with time zone not null
);
create index idx_advertiser_password_resets_advertiser
    on advertiser_password_resets (advertiser_id, created_at desc);
