-- Phase 1 users 테이블 (기존 Hibernate ddl-auto 로 만들던 것을 Flyway 로 이관)
create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    password_hash varchar(255) not null,
    name          varchar(255) not null,
    phone         varchar(255),
    role          varchar(20)  not null,
    plan          varchar(20)  not null,
    created_at    timestamp(6) with time zone not null
);
