-- Phase 2A: 독립 폼(재사용) + 폼 본문 블록
-- form: 랜딩과 별개로 만드는 입력 양식. form_type 으로 유형 확장(BASIC/STEP/...).
create table forms (
    id                         bigint generated by default as identity primary key,
    owner_id                   bigint not null references users (id),
    name                       varchar(255) not null,
    form_type                  varchar(30)  not null,
    require_phone_verification boolean      not null default false,
    consent_config             jsonb,
    submit_button_config       jsonb,
    success_config             jsonb,
    type_config                jsonb,
    created_at                 timestamp(6) with time zone not null,
    updated_at                 timestamp(6) with time zone not null
);

create index idx_forms_owner on forms (owner_id);

-- form_blocks: 폼 본문 = 순서 있는 블록 배열 (입력 항목 FIELD + 콘텐츠 IMAGE/HTML/TEXT/DIVIDER 혼합)
create table form_blocks (
    id           bigint generated by default as identity primary key,
    form_id      bigint  not null references forms (id) on delete cascade,
    step_no      integer,
    sort_order   integer not null,
    block_type   varchar(20) not null,
    field_type   varchar(30),
    label        varchar(255),
    required     boolean not null default false,
    unique_check boolean not null default false,
    placeholder  varchar(255),
    options      jsonb,
    content      jsonb
);

create index idx_form_blocks_form on form_blocks (form_id);
