-- 동의/약관 문서: 폼의 동의 항목 '보기' 링크로 연결하는, 서비스 내에서 만드는 페이지
create table consent_documents (
    id         bigint generated by default as identity primary key,
    owner_id   bigint not null references users (id),
    title      varchar(255) not null,
    content    text not null default '',
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

create index idx_consent_documents_owner on consent_documents (owner_id);
