-- 리드폼·랜딩페이지 폴더(계층형, depth 무제한). kind 로 랜딩용/리드폼용 트리를 분리한다.
-- 폴더 삭제 시 하위 폴더는 함께 삭제(on delete cascade), 안에 있던 랜딩/리드폼은 삭제하지 않고
-- 미분류로 되돌린다(on delete set null).

create table folders (
    id          bigint generated by default as identity primary key,
    owner_id    bigint not null references users (id),
    kind        varchar(20) not null,   -- LANDING | FORM
    parent_id   bigint references folders (id) on delete cascade,
    name        varchar(100) not null,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null
);
create index idx_folders_owner_kind on folders (owner_id, kind);
create index idx_folders_parent on folders (parent_id);

alter table landing_pages add column folder_id bigint references folders (id) on delete set null;
alter table forms add column folder_id bigint references folders (id) on delete set null;
create index idx_landing_pages_folder on landing_pages (folder_id);
create index idx_forms_folder on forms (folder_id);
