-- 리드(수집 데이터): 방문자가 공개 폼을 제출해 쌓이는 실제 상담 DB
create table leads (
    id              bigint generated by default as identity primary key,
    form_id         bigint not null references forms (id),
    landing_page_id bigint,                      -- Phase 3에서 랜딩 연결 시 채움(지금은 폼 단독 → null)
    answers         jsonb  not null default '[]',-- 제출 값: [{label, fieldType, value}]
    consents        jsonb,                       -- 동의 결과: [{title, required, agreed}]
    status          varchar(20) not null default 'NEW', -- NEW | NORMAL | SPAM (분류)
    phone_verified  boolean not null default false,
    group_tag       varchar(255),
    -- 방문자 정보
    submitter_ip    varchar(64),
    user_agent      varchar(1024),
    device          varchar(20),                 -- PC | MOBILE | TABLET
    os              varchar(40),
    browser         varchar(40),
    language        varchar(40),
    referer         varchar(1024),
    utm             jsonb,                        -- {source, medium, campaign, term, content}
    created_at      timestamp(6) with time zone not null
);

create index idx_leads_form on leads (form_id);
create index idx_leads_created on leads (created_at);
