-- Phase 3: 랜딩페이지 — 이미지/텍스트/HTML + '폼' 블록을 순서대로 배치한 공개 페이지
create table landing_pages (
    id           bigint generated by default as identity primary key,
    owner_id     bigint not null references users (id),
    title        varchar(255) not null,
    slug         varchar(120) not null unique,   -- 공개 주소 /p/{slug}
    content      jsonb not null default '[]',    -- 블록 배열: [{type: IMAGE|TEXT|HTML|FORM, ...}]
    status       varchar(20) not null default 'published', -- draft | published
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null
);

create index idx_landing_pages_owner on landing_pages (owner_id);
