-- 방문(유입) 로그: 공개 랜딩/폼이 열릴 때 남는 방문 기록 → 전환율(방문 대비 접수) 통계용
create table visits (
    id              bigint generated by default as identity primary key,
    owner_id        bigint not null,             -- 통계 스코프(랜딩/폼 소유자)
    landing_page_id bigint,                      -- 랜딩 방문이면 채움
    form_id         bigint,                      -- 단독 공개 폼 방문이면 채움
    -- 방문자 정보
    device          varchar(20),                 -- PC | MOBILE | TABLET
    os              varchar(40),
    browser         varchar(40),
    language        varchar(40),
    referer         varchar(1024),
    utm             jsonb,                        -- {source, medium, campaign, term, content}
    ip_hash         varchar(64),                 -- IP는 원본 대신 해시만 저장(개인정보 최소화)
    created_at      timestamp(6) with time zone not null
);

create index idx_visits_owner_created on visits (owner_id, created_at);
create index idx_visits_landing on visits (landing_page_id);
create index idx_visits_form on visits (form_id);
